### ISSUE TITLE
integrate google forms with web frontend

### ISSUE THREAD

**Issue by johannbarbie** [37coins/37coins-web#11]
allow surveys on the page that will be directed to google forms.

**Comment by VonIobro** [comment]
This was addresses for Gateways in November. 637401b6db1ff2ed82af4753cb8020cc77c5bed5

**Comment by VonIobro** [comment]
![uploads/3a2a390e-9a7a-4fc9-8097-94033eace979/blob](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F3a2a390e-9a7a-4fc9-8097-94033eace979%2Fblob)
