### ISSUE TITLE
Update Mission Statement on Website 

### ISSUE THREAD

**Issue by Gateway85** [37coins/37coins-web#15]
Mustak: Wait for Jonathan's input

**Comment by Gateway85** [comment]
New mission statement: 

"With a focus on social equity, 37coins leverages new technologies to improve access to financial services for the world’s unbanked and underbanked.
37coin’s first product is a crypto-currency based mobile money system that is easy to use, secure and accessible to anyone with a simple feature phone."


--> should be replacing the text here: 
https://www.37coins.com/en/about

**Comment by mahmed0715** [comment]
Done!
Tested locally.
did pull request branch m#15 with develop

**Comment by Gateway85** [comment]
Text should either be block (meaning all lines end at the same hight) if that does not look good we can still discuss other options. 

Space between text and the different icons should be bigger. something like 1 size of the icons seems appropriate to me. 
![uploads/4e2b5102-7394-4170-9811-469dc5831e9f/Screen Shot 2015-02-11 at 16.54.24.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F4e2b5102-7394-4170-9811-469dc5831e9f%2FScreen+Shot+2015-02-11+at+16.54.24.png)

**Comment by Gateway85** [comment]
It is updated, new issue opened for beautification part.

**Comment by Gateway85** [comment]
Screenshot from production

![uploads/619f992d-7db5-482f-84c7-625d9ec69329/Screen Shot 2015-02-12 at 16.41.50.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F619f992d-7db5-482f-84c7-625d9ec69329%2FScreen+Shot+2015-02-12+at+16.41.50.png)
