### ISSUE TITLE
Update of the team of 37coins team

### ISSUE THREAD

**Issue by Gateway85** [37coins/37coins-web#20]
Input from Jonathan

https://qa.37coins.com/en/about

**Comment by VonIobro** [comment]
Ok. Attached is a rough outline of the changes. Most of this information
can be pulled from the existing About template. Please pay attention to the
order of each profile.

Thanks,
Jonathan


## TODO
1. Need a photo and twitter information from @Miriam.
2. Need  confirmation of changes from @Johann.

## ROUGH FORMAT
<b>Johann Barbie</b>
Co-founder CEO, CTO
twitter | linked in
johann@37coins.com

<b>Jonathan Zobro</b>
Co-founder, COO
twitter | linked in
jonathan@37coins.com

<b>Miriam Grundig</b>
Program Manager
twitter
www.linkedin.com/pub/miriam-grundig/54/68a/34
miriam@37coins.com

<b>Songyi Lee</b>
Co-founder, Advisor NGO Relations
twitter
linked in







On Tue, Feb 10, 2015 at 2:49 PM, Miriam <notifications@github.com> wrote:

> Input from Jonathan
>
> https://qa.37coins.com/en/about
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/37coins/37coins-web/issues/20>.
>



-- 
Jonathan Zobro
(+1) 617-294-9375

**Comment by mahmed0715** [comment]
Done!
Tested locally.
New branch m#20 pushed, Made Pull request.

**Comment by VonIobro** [comment]
The link for Miram's LinkedIn doesn't work. Also if Miriam doesn't have a Twitter account, let's remove the <a> tag from her twitter.

**Comment by Gateway85** [comment]
Update works in production. 
Link to LinkedIn Pages and Twitter work, too. 

![uploads/116f8df6-0618-461f-8444-b649bfb7ac0a/Screen Shot 2015-02-12 at 16.29.18.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F116f8df6-0618-461f-8444-b649bfb7ac0a%2FScreen+Shot+2015-02-12+at+16.29.18.png)
