### ISSUE TITLE
Clean up Sign-Up panel

### ISSUE THREAD

**Issue by Gateway85** [37coins/37coins-web#25]
Sign-Up panel seems to be grabbing wrong CSS? (looks a bit weired now, too many shadows) 

![uploads/e0207c5f-5666-4670-8b51-e4a7bb43837d/Screen Shot 2015-02-11 at 11.36.28.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fe0207c5f-5666-4670-8b51-e4a7bb43837d%2FScreen+Shot+2015-02-11+at+11.36.28.png)

Before submitting a pull request, please let me know how the result is about to look...

**Comment by mahmed0715** [comment]
![signuptest](https://cloud.githubusercontent.com/assets/2967789/6148194/8d4dfb62-b229-11e4-952c-222b1f4e0747.png)
Is this okay?

**Comment by Gateway85** [comment]
Hi Muskat, 
Yes that is fine for now... (I would like to further improve this in future...) 

Can we merge this into the development branch, too?

**Comment by Gateway85** [comment]
good in staging.

**Comment by Gateway85** [comment]
![uploads/6ce06441-222d-4787-a1aa-c6e21d074f7e/Screen Shot 2015-03-09 at 12.40.29.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F6ce06441-222d-4787-a1aa-c6e21d074f7e%2FScreen+Shot+2015-03-09+at+12.40.29.png)

**Comment by Gateway85** [comment]
verified in production 

![uploads/9b5c34b1-0b0a-4463-a20f-ee5966a22074/Screen Shot 2015-04-14 at 12.17.40.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F9b5c34b1-0b0a-4463-a20f-ee5966a22074%2FScreen+Shot+2015-04-14+at+12.17.40.png)
