### ISSUE TITLE
Beautify Mission Statement 

### ISSUE THREAD

**Issue by Gateway85** [37coins/37coins-web#28]
The text should be in block making it look more clean. Space between text and contact info should be bigger (suggestion: as big as the first icon)

**Comment by Gateway85** [comment]
![uploads/bbee0ed9-4b3b-4d00-a8a6-a4f61063a78c/Screen Shot 2015-02-12 at 16.41.50.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fbbee0ed9-4b3b-4d00-a8a6-a4f61063a78c%2FScreen+Shot+2015-02-12+at+16.41.50.png)

**Comment by mahmed0715** [comment]
This is already done.
Pull request #29

**Comment by Gateway85** [comment]
Looks good now 
![uploads/eccfa91e-ba48-46f5-aa91-8a26da052c79/Screen Shot 2015-02-16 at 15.41.45.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Feccfa91e-ba48-46f5-aa91-8a26da052c79%2FScreen+Shot+2015-02-16+at+15.41.45.png)

**Comment by Gateway85** [comment]
done and in production
