### ISSUE TITLE
Help Panel should be Left-aligned

### ISSUE THREAD

**Issue by VonIobro** [37coins/37coins-web#32]
Right now one of the updates to the CSS changed it to being centered.

Once this is corrected, double check the Log-in panels to ensure that it doesn't negatively effect them.  (or make sure there is a custom selector)

![uploads/781cbf63-8632-4305-afb8-e817b5f16f7a/blob](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F781cbf63-8632-4305-afb8-e817b5f16f7a%2Fblob)

**Comment by mahmed0715** [comment]
Pull Request submitted!

**Comment by Gateway85** [comment]
corrected in staging environment

**Comment by Gateway85** [comment]
verified in production 

![uploads/8a41c262-0abb-4530-8055-38a5a1e1c739/Screen Shot 2015-04-14 at 12.15.58.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F8a41c262-0abb-4530-8055-38a5a1e1c739%2FScreen+Shot+2015-04-14+at+12.15.58.png)
