### ISSUE TITLE
Have another dialog before an account/gateway/market is deleted

### ISSUE THREAD

**Issue by Gateway85** [37coins/37coins-web#37]
Make user aware that deletion is complete and not undoable

**Comment by mahmed0715** [comment]
Done!
Pull request sent!
Popup looks like:
![deletion popup](https://cloud.githubusercontent.com/assets/2967789/6367807/d51c2630-bd00-11e4-8d12-f7c754ddac05.png)

**Comment by Gateway85** [comment]
verified in staging... 

![uploads/f3e36446-fc74-460a-8927-36132661c967/Screen Shot 2015-03-09 at 12.35.39.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Ff3e36446-fc74-460a-8927-36132661c967%2FScreen+Shot+2015-03-09+at+12.35.39.png)

**Comment by Gateway85** [comment]
verified in production. 

![uploads/e5c64136-dccc-4ec3-8110-977ec0fe814b/Screen Shot 2015-04-14 at 12.12.22.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fe5c64136-dccc-4ec3-8110-977ec0fe814b%2FScreen+Shot+2015-04-14+at+12.12.22.png)
