### ISSUE TITLE
Admin Interface: Delete all occurences of an account in the different systems (rambutan, kiwi)

### ISSUE THREAD

**Issue by Gateway85** [37coins/37coins-web#40]
Oscar implemented the backend support for that.

**Comment by Gateway85** [comment]
support for this via rest api has been developed by Oscar (ask him for details) 
this REST API is missing the key authentication for the kiwi part, but Oscar will add this and then we can add it too. 

No account should be deleted if there are still bitcoins in it.

**Comment by oscarguindzberg** [comment]
Related to https://github.com/37coins/kiwi-chains/issues/140

**Comment by oscarguindzberg** [comment]
Kiwi account should be deleted first, and if that works fine, delete rambutan accounts

**Comment by oscarguindzberg** [comment]
These issues are related/duplicated. Should we reorganize them?
https://github.com/37coins/37coins/issues/325
https://github.com/37coins/37coins/issues/283
https://github.com/37coins/37coins-web/issues/40

**Comment by Gateway85** [comment]
authtoken, transaction history

**Comment by Gateway85** [comment]
Closing as duplicate of 37coins #325
