### ISSUE TITLE
Admin password is placed in URL

### ISSUE THREAD

**Issue by troggy** [37coins/37coins-web#51]
That's awefull security hole.

**Comment by johannbarbie** [comment]
aren't we just using basic auth, where is that?

**Comment by troggy** [comment]
I didn't look deeper, I just glanced at URL string in my browser and
noticed plain text password there

**Comment by johannbarbie** [comment]
which url is that?

**Comment by troggy** [comment]
Yes, sorry.. seem to be KeePass issue on my machine
