### ISSUE TITLE
API Doc: scrolling over left-side headings does the wrong thing

### ISSUE THREAD

**Issue by Gateway85** [37coins/37coins-web#57]
when clicking on Introduction, Introduction is scrolled away and next topic is in focus... 

![uploads/1c71f9d4-a697-48d7-a7e2-e242e450d6cb/Screen Shot 2015-03-27 at 16.21.34.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F1c71f9d4-a697-48d7-a7e2-e242e450d6cb%2FScreen+Shot+2015-03-27+at+16.21.34.png)

**Comment by mahmed0715** [comment]
Done.

**Comment by Gateway85** [comment]
verified on api.37coins.io --> works good.
