### ISSUE TITLE
API: beautifications

### ISSUE THREAD

**Issue by Gateway85** [37coins/37coins-web#70]
1) Signing Oracle. --> heading is different to other headings, please adjust and remove the period at the end of it
2) It should be possible to close the chains Api Docs again after opening, so one can go to the oracle Api Docs without scrolling
3) chains and oracle should be spelled with a capital letter (if possible)
4) Going back to main introduction should also be possible from menu on the left
5) can scrolling in menu be independent from scrolling in the content pane?

**Comment by Gateway85** [comment]
1) solved

**Comment by mahmed0715** [comment]
Pls check.
1-4 and 6 solved.
for 5: on scroll on the right pane should not affect left menu, right?  or what?

**Comment by mahmed0715** [comment]
2: on click on the menu again will toggle..
