### ISSUE TITLE
API: Have FAV symbol on web URL 

### ISSUE THREAD

**Issue by Gateway85** [37coins/37coins-web#82]
![uploads/1ff05b65-2614-4d2e-92c1-715a2ac6b622/Screen Shot 2015-04-17 at 17.08.35.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F1ff05b65-2614-4d2e-92c1-715a2ac6b622%2FScreen+Shot+2015-04-17+at+17.08.35.png)

**Comment by mahmed0715** [comment]
added FAV, Pushed in develop branch.

**Comment by mahmed0715** [comment]
how do you check develop branch?

**Comment by Gateway85** [comment]
--> moved to github.io as issue #5
